"""added user type

Revision ID: afe5c030bcb2
Revises: 
Create Date: 2020-04-23 10:29:22.739754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe5c030bcb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdetails', sa.Column('usertype', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdetails', 'usertype')
    # ### end Alembic commands ###
